name: my_notes
description: "my notes with flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  bottom_sheet: ^4.0.0
  sqflite: ^2.3.2
  flutter_conditional: ^1.0.0+2
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  sqflite_common_ffi: any
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  http: ^1.1.0
  hexcolor: ^3.0.1
  intl: ^0.17.0
  toast: ^0.3.0
  alarm: ^3.0.12
  date_time_picker: ^2.1.0
  flutter_local_notifications: ^17.0.0
  flutter_timezone: ^1.0.8
   
 




dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/audio/
  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-VariableFont_wght.ttf
    - family: Whisper
      fonts:
        - asset: assets/fonts/Whisper-Regular.ttf